FROM quay.io/alwaystherookie/toolbox-images:base

RUN dnf -y install pass kubernetes-client jq python2 make vim bind-utils postgresql

RUN dnf -y install https://prerelease.keybase.io/keybase_amd64.rpm
