FROM quay.io/alwaystherookie/toolbox-images:base

RUN dnf -y install pass kubernetes-client python2 postgresql python3-yaml python3-pytest protobuf-devel

RUN dnf -y install https://prerelease.keybase.io/keybase_amd64.rpm
